# Generated by Django 5.0.1 on 2024-01-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_date',
        ),
    ]
